### ISSUE TITLE
Insecure PRNG

### ISSUE THREAD

**Issue by dchest** [antelle/kdbxweb#5]
Mixing a bunch of `Math.random` with Salsa20 doesn't make PRNG secure. Please use `crypto.getRandomValues` in browser and `crypto.randomBytes` in Node, for example:

```javascript
  var getRandomBytes = (
    (typeof self !== 'undefined' && (self.crypto || self.msCrypto))
      ? function() { // Browsers
          var crypto = (self.crypto || self.msCrypto), QUOTA = 65536;
          return function(n) {
            var a = new Uint8Array(n);
            for (var i = 0; i < n; i += QUOTA) {
              crypto.getRandomValues(a.subarray(i, i + Math.min(n - i, QUOTA)));
            }
            return a;
          };
        }
      : function() { // Node
          return require("crypto").randomBytes;
        }
  )();
```

This will give you random bytes:

```javascript
aesKey = getRandomBytes(18)
```

**Comment by antelle** [comment]
Thank you, I'll replace it of course.

**Comment by antelle** [comment]
I've added system generator usage. But I'll leave XOR'ing it with Salsa20, to prevent backdoors which might be inserted into such 'recommended' functions. Anyway, XORing will never make a sequence less secure.

**Comment by cxxr** [comment]
Why are you XORing the PRNG with the CSRNG?

**Comment by dchest** [comment]
This doesn't make any sense. If you're worried that browser's random source has a backdoor, XORing with Salsa20 stream keyed by the same backdoored random source will get you nothing.

**Comment by eligrey** [comment]
Please simply use crypto.getRandomValues by itself. You can't trust one API provided by your browser more than another API provided by your browser.

If your browser is compromised, then your browser is compromised. **There is no workaround to a compromised browser**, so please do not attempt to do anything about it.

**Comment by antelle** [comment]
> Why are you XORing the PRNG with the CSRNG?

Why not? This will never make it weaker.
> If you're worried that browser's random source has a backdoor, XORing with Salsa20 stream keyed by the same backdoored random source will get you nothing.

I'm afraid, you are wrong here. If we use backdoored random source, combining it with some less or more random sequence will make the backdoor useless.
> Salsa20 is not some magic thing that will add entropy

Of course but data is taken from random position of it.
> Please simply use crypto.getRandomValues by itself.

Why? There's no disadvantage of XORing. Is there any?
> It is illogical to trust one API provided by your browser more than another API

Which API is trusted more? Another algorithms, like AES, cannot be modified in any way, unlike random. Browser might use system built-in random, which might use recommended generator, which we would not like to use.

**Comment by eligrey** [comment]
> Which API is trusted more?

You said yourself that you think crypto.getRandomValues needs backdoor mitigation:

> to prevent backdoors which might be inserted into such 'recommended' functions

In response to:

> Of course but data is taken from random position of it, so it will alter the random sequence.

What is the benefit of that to you? Entropy has not increased and an attacker knows exactly how you used Salsa20 so it literally provides zero security benefit.

> There is a workaround for compromised algorithm. This way of defense (mix with another cipher) is written in some papers, and even in Wikipedia: https://en.wikipedia.org/wiki/Random_number_generator_attack

Yes, that is a real mitigation but it only helps with closed source server-side software. This app is open source and everyone knows exactly what steps your algorithm takes.

**Comment by antelle** [comment]
> What is the benefit of that to you? Entropy has not increased.

Entropy is increased because we use salsa20 with:
1. random nonce
2. with a value depending on usage count

Well, let's even suppose that 'it literally provides zero security benefit': it does not provide any drawbacks, do you agree with that?

**Comment by antelle** [comment]
Just to clarify.
The way RNG backdoors work: we have a certain sequence by which we can guess and try to match, so the result effort will be O(N) where N is the length of the sequence. Pretty easy.
If we mix (xor) the result with some another sequence generated by other algorithm, the attack effort becomes O(N*M) where M is the length of another sequence (for Salsa20 it's 2^64).

**Comment by hameerabbasi** [comment]
This is old, but perhaps provide an option? Default to whichever you like, but allow the tech-savvy user to select which he wishes to use.

**Comment by antelle** [comment]
This must be implemented as a plugin, once we support them...
