### ISSUE TITLE
import from KeepassX

### ISSUE THREAD

**Issue by exromany** [antelle/kdbxweb#7]
Hi @antelle , I want to implement ability to import db from xml-file with KeepassX database.
Do you have any ideas about right place and interface for this functionality?

**Comment by antelle** [comment]
Hm, but you have already made loading xml in #6  
What do you mean as import?

**Comment by exromany** [comment]
I mean load xml with another format - KeepassX wich compatible with keepass 1.x

**Comment by antelle** [comment]
I got it, you mean KDBv1. This is not XML, this is binary format which was supported by earlier versions of KeePass. There're no plans to implement it support, as this will overcomplicate the library. The users can always convert between them.

**Comment by exromany** [comment]
not exactly. I mean to import XML exported from KeepassX

**Comment by antelle** [comment]
KeePassX should export KDBX files in the same format as KeePass. We don't want to support XML which is produced while exporting KDBv1 files.

**Comment by antelle** [comment]
Additional thought: I have plans to import CSV and other format files, so such XML can be added as an option as well. This would be implemented as a converter library, capable to open different format files. So different types of XML could be added in such way..
